repos:
  - repo: local
    hooks:
      - id: render
        name: Render README.md
        description: Runs render.py to re-create the README
        entry: python render.py
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
