name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          cache: "pip"
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
