name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      - name: Install Python requirements
        run: pip install -r requirements.txt
      - name: Install Javascript requirements
        run: npm install
      - name: Run pre-commit hooks
        run: pre-commit run --all-files
